/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWebDevelopmentRouteImport } from './routes/services.web-development'
import { Route as ServicesAiPodcastRouteImport } from './routes/services.ai-podcast'
import { Route as ServicesAiIntegratorRouteImport } from './routes/services.ai-integrator'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebDevelopmentRoute = ServicesWebDevelopmentRouteImport.update({
  id: '/services/web-development',
  path: '/services/web-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiPodcastRoute = ServicesAiPodcastRouteImport.update({
  id: '/services/ai-podcast',
  path: '/services/ai-podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiIntegratorRoute = ServicesAiIntegratorRouteImport.update({
  id: '/services/ai-integrator',
  path: '/services/ai-integrator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services/ai-integrator': typeof ServicesAiIntegratorRoute
  '/services/ai-podcast': typeof ServicesAiPodcastRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services/ai-integrator': typeof ServicesAiIntegratorRoute
  '/services/ai-podcast': typeof ServicesAiPodcastRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services/ai-integrator': typeof ServicesAiIntegratorRoute
  '/services/ai-podcast': typeof ServicesAiPodcastRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services/ai-integrator'
    | '/services/ai-podcast'
    | '/services/web-development'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services/ai-integrator'
    | '/services/ai-podcast'
    | '/services/web-development'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/services/ai-integrator'
    | '/services/ai-podcast'
    | '/services/web-development'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesAiIntegratorRoute: typeof ServicesAiIntegratorRoute
  ServicesAiPodcastRoute: typeof ServicesAiPodcastRoute
  ServicesWebDevelopmentRoute: typeof ServicesWebDevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-development': {
      id: '/services/web-development'
      path: '/services/web-development'
      fullPath: '/services/web-development'
      preLoaderRoute: typeof ServicesWebDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-podcast': {
      id: '/services/ai-podcast'
      path: '/services/ai-podcast'
      fullPath: '/services/ai-podcast'
      preLoaderRoute: typeof ServicesAiPodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-integrator': {
      id: '/services/ai-integrator'
      path: '/services/ai-integrator'
      fullPath: '/services/ai-integrator'
      preLoaderRoute: typeof ServicesAiIntegratorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesAiIntegratorRoute: ServicesAiIntegratorRoute,
  ServicesAiPodcastRoute: ServicesAiPodcastRoute,
  ServicesWebDevelopmentRoute: ServicesWebDevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
