/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServicesWebDevelopmentRouteImport } from './routes/services.web-development'
import { Route as ServicesAiPodcastRouteImport } from './routes/services.ai-podcast'
import { Route as ServicesAiIntegratorRouteImport } from './routes/services.ai-integrator'
import { Route as SampleSlugRouteImport } from './routes/sample.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminSampleBuilderRouteImport } from './routes/admin.sample-builder'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebDevelopmentRoute = ServicesWebDevelopmentRouteImport.update({
  id: '/services/web-development',
  path: '/services/web-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiPodcastRoute = ServicesAiPodcastRouteImport.update({
  id: '/services/ai-podcast',
  path: '/services/ai-podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiIntegratorRoute = ServicesAiIntegratorRouteImport.update({
  id: '/services/ai-integrator',
  path: '/services/ai-integrator',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleSlugRoute = SampleSlugRouteImport.update({
  id: '/sample/$slug',
  path: '/sample/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSampleBuilderRoute = AdminSampleBuilderRouteImport.update({
  id: '/admin/sample-builder',
  path: '/admin/sample-builder',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/admin/sample-builder': typeof AdminSampleBuilderRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/sample/$slug': typeof SampleSlugRoute
  '/services/ai-integrator': typeof ServicesAiIntegratorRoute
  '/services/ai-podcast': typeof ServicesAiPodcastRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/admin/sample-builder': typeof AdminSampleBuilderRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/sample/$slug': typeof SampleSlugRoute
  '/services/ai-integrator': typeof ServicesAiIntegratorRoute
  '/services/ai-podcast': typeof ServicesAiPodcastRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/admin/sample-builder': typeof AdminSampleBuilderRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/sample/$slug': typeof SampleSlugRoute
  '/services/ai-integrator': typeof ServicesAiIntegratorRoute
  '/services/ai-podcast': typeof ServicesAiPodcastRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/admin/sample-builder'
    | '/blog/$slug'
    | '/sample/$slug'
    | '/services/ai-integrator'
    | '/services/ai-podcast'
    | '/services/web-development'
    | '/blog/'
    | '/projects/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/admin/sample-builder'
    | '/blog/$slug'
    | '/sample/$slug'
    | '/services/ai-integrator'
    | '/services/ai-podcast'
    | '/services/web-development'
    | '/blog'
    | '/projects'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/admin/sample-builder'
    | '/blog/$slug'
    | '/sample/$slug'
    | '/services/ai-integrator'
    | '/services/ai-podcast'
    | '/services/web-development'
    | '/blog/'
    | '/projects/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  AdminSampleBuilderRoute: typeof AdminSampleBuilderRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SampleSlugRoute: typeof SampleSlugRoute
  ServicesAiIntegratorRoute: typeof ServicesAiIntegratorRoute
  ServicesAiPodcastRoute: typeof ServicesAiPodcastRoute
  ServicesWebDevelopmentRoute: typeof ServicesWebDevelopmentRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-development': {
      id: '/services/web-development'
      path: '/services/web-development'
      fullPath: '/services/web-development'
      preLoaderRoute: typeof ServicesWebDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-podcast': {
      id: '/services/ai-podcast'
      path: '/services/ai-podcast'
      fullPath: '/services/ai-podcast'
      preLoaderRoute: typeof ServicesAiPodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-integrator': {
      id: '/services/ai-integrator'
      path: '/services/ai-integrator'
      fullPath: '/services/ai-integrator'
      preLoaderRoute: typeof ServicesAiIntegratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample/$slug': {
      id: '/sample/$slug'
      path: '/sample/$slug'
      fullPath: '/sample/$slug'
      preLoaderRoute: typeof SampleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sample-builder': {
      id: '/admin/sample-builder'
      path: '/admin/sample-builder'
      fullPath: '/admin/sample-builder'
      preLoaderRoute: typeof AdminSampleBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  AdminSampleBuilderRoute: AdminSampleBuilderRoute,
  BlogSlugRoute: BlogSlugRoute,
  SampleSlugRoute: SampleSlugRoute,
  ServicesAiIntegratorRoute: ServicesAiIntegratorRoute,
  ServicesAiPodcastRoute: ServicesAiPodcastRoute,
  ServicesWebDevelopmentRoute: ServicesWebDevelopmentRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
