// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://batdoueyliuahykjoczk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhdGRvdWV5bGl1YWh5a2pvY3prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5ODA3NTMsImV4cCI6MjA4ODU1Njc1M30.16cOQbfgEiZ2kld9FtZqqjr0oN-XRX03KPcmVS0BIiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});