// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuqqfgngrwduzxrffyhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1cXFmZ25ncndkdXp4cmZmeWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE5NDU3MjUsImV4cCI6MjA5NzUyMTcyNX0.xh4Ftebp4mV0jf9-7rvN3r-uzOcoZna11r9EY4JA1ig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});